# Generated by Django 5.0.6 on 2024-10-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_created_at_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='imgs/undraw_profile.svg', max_length=100, verbose_name='Imagen de Perfil Predeterminada.'),
        ),
    ]
