# Generated by Django 4.2.17 on 2024-12-15 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
    ]
