# Generated by Django 4.2.17 on 2024-12-14 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregisters', '0002_alter_arqueo_usuario_alter_movimiento_tipo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed')], default='closed', max_length=10, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('user_made', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cashregisters.cashregister')),
                ('user_made', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='caja',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='user_made',
        ),
        migrations.DeleteModel(
            name='Arqueo',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
