# Generated by Django 5.1.4 on 2024-12-24 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregisters', '0005_alter_cashregister_user_made_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('theorical_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('physical_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='cashregisters.cashregister', verbose_name='Arqueos')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_made', to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
